apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    helm.sh/chart: {{ include "..chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "..name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "..name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      initContainers:
        - name: "init-{{ .Chart.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
            - /bin/bash
            - /run.sh
          args:
            - configure
            - -J-Ddisable.configuration.wizard.on.clean.install=true
            - --listen-port=8080
          volumeMounts:
            - name: "{{ include "..fullname" . }}-conf"
              mountPath: /opt/youtrack/conf
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: ["/bin/bash", "/run.sh"]
          volumeMounts:
            - name: "{{ include "..fullname" . }}-data"
              mountPath: /opt/youtrack/data
            - name: "{{ include "..fullname" . }}-conf"
              mountPath: /opt/youtrack/conf
            - name: "{{ include "..fullname" . }}-logs"
              mountPath: /opt/youtrack/logs
            - name: "{{ include "..fullname" . }}-backups"
              mountPath: /opt/youtrack/backups
      volumes:
        - name: "{{ include "..fullname" . }}-data"
          persistentVolumeClaim:
            claimName: "efs-claim-{{ include "..fullname" . }}-data"
        - name: "{{ include "..fullname" . }}-conf"
          persistentVolumeClaim:
            claimName: "efs-claim-{{ include "..fullname" . }}-conf"
        - name: "{{ include "..fullname" . }}-logs"
          persistentVolumeClaim:
            claimName: "efs-claim-{{ include "..fullname" . }}-logs"
        - name: "{{ include "..fullname" . }}-backups"
          persistentVolumeClaim:
            claimName: "efs-claim-{{ include "..fullname" . }}-backups"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
