# {{- $useExisitingVolume := and .Values.existingVolumes.enabled (ne .Values.existingVolumes.backups "") }}
# {{- if $useExisitingVolume -}}
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: "sc-{{ include "..fullname" . }}-backups"
#   annotations:
#     "helm.sh/hook": "pre-install"
# provisioner: efs.csi.aws.com
# parameters:
#   type: gp2
# reclaimPolicy: Retain
# mountOptions:
#   - debug
# volumeBindingMode: Immediate
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: "pv-{{ include "..fullname" . }}-backups"
#   labels:
#     type: amazonEFS
#   annotations:
#     "helm.sh/hook": "pre-install"
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: "sc-{{ include "..fullname" . }}-backups"
#   csi:
#     driver: efs.csi.aws.com
#     volumeHandle: fs-8e4b7563
# ---
# {{- end -}}
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: "pvc-{{ include "..fullname" . }}-backups"
#   annotations:
#     "helm.sh/hook": "pre-install"
# spec:
#   {{- if $useExisitingVolume }}
#   storageClassName: "sc-{{ include "..fullname" . }}-backups"
#   {{- end }}
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc-backups
  annotations:
    "helm.sh/hook": "pre-install"
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "efs-claim-{{ include "..fullname" . }}-backups"
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  # {{- if $useExisitingVolume }}
  # storageClassName: "sc-{{ include "..fullname" . }}-backups"
  # {{- end }}
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-backups
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-{{ include "..fullname" . }}-backups
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-backups
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efs_ids.backups }}
