# see https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml
# see https://argoproj.github.io/argo-cd/operator-manual/ingress/#aws-application-load-balancers-albs-and-classic-elb-http-mode
server:
  replicas: 1

  ingress:
    enabled: true
    apiVersion: extensions/v1beta1

    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ca-central-1:491327797652:certificate/05414c50-3a2a-4c0e-aca3-b2fc717561ca"
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
      # see https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/tasks/ssl_redirect/
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      external-dns.alpha.kubernetes.io/hostname: "argocd.buttoncloud.ca"

    hosts:
      - argocd.buttoncloud.ca

    paths:
      - /*

    # see https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
    extraPaths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation

  extraArgs:
    - --insecure
